name = input()
id = int(input())
group = int(id // 100)
bed = int(id // 10 % 10)
id_children = int(id % 10)
print(f"Группа №{group}.")
print(f"{id_children}. {name}.")
print(f"Шкафчик: {id}.")
print(f"Кроватка: {bed}.")
